### PR TITLE
fix(index): Support namespace and package parameters

### LINKED ISSUE #30: Support namespace and package parameters
Currently, the namespace and package for the "type" to JSON OW action are hardcoded (see [here](https://github.com/adobe/helix-index-files/blob/bcee5ee74b61ade43648d300ed324b831f197c4d/src/index.js#L70))

Instead, it should be possible to pass them as parameters, and their default values should be derived from the action invoked.

### PR DESCRIPTION
**Pull request by dominique-pfister**
fix #30

### CODE REVIEW

File: src/index.js [hunk 1]
```diff
@@ -59,32 +59,36 @@ async function loadConfig(owner, repo, ref) {
...
-    console.error('Missing parameters', owner, repo, ref, branch, path, paths, token, sha, !!ALGOLIA_APP_ID, !!ALGOLIA_API_KEY);
+    console.error('Missing parameters', owner, repo, ref, branch, path, paths, sha, !!ALGOLIA_APP_ID, !!ALGOLIA_API_KEY);
     throw new Error('Missing required parameters');
   }
 
+  const regex = /\/([^/]+)\/((.*)\/)?([^/]+)/;
+
+  // eslint-disable-next-line no-underscore-dangle
+  const result = process.env.__OW_ACTION_NAME.match(regex);
+
```
Comment (tripodsan) [inline src/index.js]:
```suggestion
const ns = namespace || process.env.__OW_NAMESPACE;
```

Comment (dominique-pfister) [reply src/index.js]: Cool, done!

**Comment by dominique-pfister** [comment]
The code didn't work for multiple paths, I refactored the very long `main()` function into separate functions, now it works with a `paths` array.
